# Generated by Django 3.1.5 on 2021-01-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bidding_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='createDate',
        ),
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
