# Generated by Django 3.1.5 on 2021-02-05 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210125_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('bid_price', models.IntegerField()),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('category', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, choices=[('user', 'User')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='noOfBidder',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='bidPrice',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='username',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='createDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bidding',
            name='itemName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.item'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='listedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_listed_by', to='auctions.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='auctions.userprofile'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='itemName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='auctions.item'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='listedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_by', to='auctions.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='itemName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_item', to='auctions.item'),
        ),
    ]
