# Generated by Django 3.1.5 on 2021-02-05 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210205_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='bid_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='comment',
        ),
        migrations.AddField(
            model_name='bidding',
            name='bidPrice',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='userComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='auctions.userprofile'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='createDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
