# Generated by Django 3.1.5 on 2021-02-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210205_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='price',
        ),
    ]
