# Generated by Django 3.1.5 on 2021-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210206_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='itemName',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='bidding',
            old_name='itemName',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='itemName',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='static/auctions/images/'),
        ),
    ]
