# Generated by Django 3.1.5 on 2021-02-06 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210206_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='createTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
