# Generated by Django 3.1.5 on 2021-02-07 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210207_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='listedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
