# Generated by Django 3.1.5 on 2021-02-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210207_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='bidCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
