# Generated by Django 3.1.5 on 2021-02-07 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bidding_bidcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='item',
            new_name='itemInfo',
        ),
        migrations.AddField(
            model_name='bidding',
            name='listingInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_info', to='auctions.auctionlisting'),
        ),
    ]
