# Generated by Django 3.1.5 on 2021-02-07 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210207_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='itemInfo',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='listedBy',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='item',
        ),
        migrations.AddField(
            model_name='comment',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='comment_item', to='auctions.Item'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='auctions.item'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='listedBy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
