# Generated by Django 3.1.5 on 2021-02-07 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210207_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='listedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
